# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mysql
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: rootroot
    volumes:
      - /Users/bhavesh/Documents/docker-server/services/mysql/dump:/dump:nocopy,delegated
      - /Users/bhavesh/Documents/docker-server/services/mysql/data:/var/lib/mysql

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 8080:8080
