version: '3.8'

services:

  nginx:
    container_name: nginx
    image: nginx:latest
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    mem_limit: 2g
    volumes:
      - project-magento243-sync:/projects/magento243:nocopy,delegated
      - project-magento243p1-sync:/projects/magento243p1:nocopy,delegated
      - project-magento234-sync:/projects/magento234:nocopy,delegated
      - project-projectx-sync:/projects/projectx:nocopy,delegated
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/magento2-cors.conf:/etc/nginx/magento2-cors.conf
    links:
      - phpfpm

  phpfpm:
    container_name: phpfpm
    # image: php:7.3-fpm
    image: php:7.4-fpm
    restart: unless-stopped
    ports:
      - 9000:9000
    mem_limit: 6g
    build:
      # context: ./php/73/ 
      context: ./php/74/ 
      dockerfile: Dockerfile
    volumes:
      - project-other-sync:/other:nocopy,delegated
      - project-magento243-sync:/projects/magento243:nocopy,delegated
      - project-magento243p1-sync:/projects/magento243p1:nocopy,delegated
      - project-magento234-sync:/projects/magento234:nocopy,delegated
      - project-projectx-sync:/projects/projectx:nocopy,delegated

volumes:
  project-other-sync:
    external: true

  project-magento243-sync:
    external: true

  project-magento243p1-sync:
    external: true

  project-magento234-sync:
    external: true

  project-projectx-sync:
    external: true
